apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-volume-claim
  labels:
    app: postgres
spec:
  storageClassName: postgres-local-storage
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume-claim
  labels:
    app: app-data
spec:
  storageClassName: app-local-storage
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany