apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume-claim
  labels:
    app: baseapp
spec:
  storageClassName: app-local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce