apiVersion: v1
kind: Service
metadata:
  name: base-service-web
spec:
  type: NodePort
  selector:
    app: baseapp
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30950
---
apiVersion: v1
kind: Service
metadata:
  name: base-service-db
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 30951



