kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: kindest/node:v1.29.0
- role: worker
  image: kindest/node:v1.29.0
  extraPortMappings:
  - containerPort: 30950
    hostPort: 8085
    listenAddress: "127.0.0.1"
    protocol: TCP
  labels:
    tier: web-node
- role: worker
  image: kindest/node:v1.29.0
  extraPortMappings:
  - containerPort: 30951
    hostPort: 8086
    listenAddress: "127.0.0.1"
    protocol: TCP
  labels:
    tier: db-node
