apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baseapp
  template:
    metadata:
      labels:
        app: baseapp
    spec:
      containers:
      - name: baseapp
        image: nginx:1.26.2
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
         - mountPath: /share/data
           name: app-data
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-volume-claim